// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240410195126_updateStoreItemModel")]
    partial class updateStoreItemModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catagory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Catagory = "Category 1",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4979),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4989),
                            Description = "Description 1",
                            IsDeleted = false,
                            ItemName = "Item 1",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4987)
                        },
                        new
                        {
                            Id = 2,
                            Catagory = "Category 2",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5012),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5015),
                            Description = "Description 2",
                            IsDeleted = false,
                            ItemName = "Item 2",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5014)
                        },
                        new
                        {
                            Id = 3,
                            Catagory = "Category 3",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5028),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5032),
                            Description = "Description 3",
                            IsDeleted = false,
                            ItemName = "Item 3",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5030)
                        },
                        new
                        {
                            Id = 4,
                            Catagory = "Category 4",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5043),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5046),
                            Description = "Description 4",
                            IsDeleted = false,
                            ItemName = "Item 4",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5044)
                        },
                        new
                        {
                            Id = 5,
                            Catagory = "Category 5",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5057),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5060),
                            Description = "Description 5",
                            IsDeleted = false,
                            ItemName = "Item 5",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5058)
                        },
                        new
                        {
                            Id = 6,
                            Catagory = "Category 6",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5078),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5081),
                            Description = "Description 6",
                            IsDeleted = false,
                            ItemName = "Item 6",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5079)
                        },
                        new
                        {
                            Id = 7,
                            Catagory = "Category 7",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5092),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5095),
                            Description = "Description 7",
                            IsDeleted = false,
                            ItemName = "Item 7",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5094)
                        },
                        new
                        {
                            Id = 8,
                            Catagory = "Category 8",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5106),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5109),
                            Description = "Description 8",
                            IsDeleted = false,
                            ItemName = "Item 8",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5108)
                        },
                        new
                        {
                            Id = 9,
                            Catagory = "Category 9",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5121),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5124),
                            Description = "Description 9",
                            IsDeleted = false,
                            ItemName = "Item 9",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5122)
                        },
                        new
                        {
                            Id = 10,
                            Catagory = "Category 10",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5141),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5144),
                            Description = "Description 10",
                            IsDeleted = false,
                            ItemName = "Item 10",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(5143)
                        });
                });

            modelBuilder.Entity("DAL.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StoreLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInformation = "Contact Info 1",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(3942),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(3968),
                            IsDeleted = false,
                            StoreLocation = "Location 1",
                            StoreName = "Store 1",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(3966)
                        },
                        new
                        {
                            Id = 2,
                            ContactInformation = "Contact Info 2",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(3992),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(3995),
                            IsDeleted = false,
                            StoreLocation = "Location 2",
                            StoreName = "Store 2",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(3993)
                        },
                        new
                        {
                            Id = 3,
                            ContactInformation = "Contact Info 3",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4007),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4010),
                            IsDeleted = false,
                            StoreLocation = "Location 3",
                            StoreName = "Store 3",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4009)
                        },
                        new
                        {
                            Id = 4,
                            ContactInformation = "Contact Info 4",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4186),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4190),
                            IsDeleted = false,
                            StoreLocation = "Location 4",
                            StoreName = "Store 4",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4189)
                        },
                        new
                        {
                            Id = 5,
                            ContactInformation = "Contact Info 5",
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4203),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4207),
                            IsDeleted = false,
                            StoreLocation = "Location 5",
                            StoreName = "Store 5",
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 838, DateTimeKind.Local).AddTicks(4205)
                        });
                });

            modelBuilder.Entity("DAL.StoreItem", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StoreId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("StoreItems");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            ItemId = 1,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8512),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8525),
                            IsDeleted = false,
                            Price = 49.71m,
                            Quantity = 10,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8524)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 2,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8595),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8600),
                            IsDeleted = false,
                            Price = 45.46m,
                            Quantity = 94,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8598)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 3,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8616),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8620),
                            IsDeleted = false,
                            Price = 23.25m,
                            Quantity = 29,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8619)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 4,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8644),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8647),
                            IsDeleted = false,
                            Price = 26.67m,
                            Quantity = 71,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8646)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 5,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8665),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8669),
                            IsDeleted = false,
                            Price = 72.58m,
                            Quantity = 46,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8667)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 6,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8697),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8700),
                            IsDeleted = false,
                            Price = 51.82m,
                            Quantity = 77,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8699)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 7,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8716),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8720),
                            IsDeleted = false,
                            Price = 3.74m,
                            Quantity = 90,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8718)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 8,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8742),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8746),
                            IsDeleted = false,
                            Price = 4.46m,
                            Quantity = 22,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8744)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 9,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8762),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8766),
                            IsDeleted = false,
                            Price = 86.46m,
                            Quantity = 61,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8764)
                        },
                        new
                        {
                            StoreId = 1,
                            ItemId = 10,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8791),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8794),
                            IsDeleted = false,
                            Price = 2.98m,
                            Quantity = 47,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8793)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 1,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8812),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8816),
                            IsDeleted = false,
                            Price = 28.91m,
                            Quantity = 56,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8814)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 2,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8837),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8841),
                            IsDeleted = false,
                            Price = 38.77m,
                            Quantity = 51,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8840)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 3,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8856),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8859),
                            IsDeleted = false,
                            Price = 65.93m,
                            Quantity = 62,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8858)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 4,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8881),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8884),
                            IsDeleted = false,
                            Price = 30.43m,
                            Quantity = 17,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8883)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 5,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8899),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8903),
                            IsDeleted = false,
                            Price = 82.86m,
                            Quantity = 72,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8901)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 6,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8924),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8928),
                            IsDeleted = false,
                            Price = 7.60m,
                            Quantity = 7,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8926)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 7,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8943),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8947),
                            IsDeleted = false,
                            Price = 71.37m,
                            Quantity = 56,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8945)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 8,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8972),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8976),
                            IsDeleted = false,
                            Price = 65.82m,
                            Quantity = 1,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8974)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 9,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8991),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8994),
                            IsDeleted = false,
                            Price = 22.40m,
                            Quantity = 6,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(8993)
                        },
                        new
                        {
                            StoreId = 2,
                            ItemId = 10,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9017),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9020),
                            IsDeleted = false,
                            Price = 21.91m,
                            Quantity = 92,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9019)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 1,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9036),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9040),
                            IsDeleted = false,
                            Price = 57.79m,
                            Quantity = 27,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9038)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 2,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9062),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9066),
                            IsDeleted = false,
                            Price = 74.95m,
                            Quantity = 85,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9064)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 3,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9081),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9085),
                            IsDeleted = false,
                            Price = 89.74m,
                            Quantity = 75,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9083)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 4,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9266),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9270),
                            IsDeleted = false,
                            Price = 14.36m,
                            Quantity = 26,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9268)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 5,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9286),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9290),
                            IsDeleted = false,
                            Price = 81.51m,
                            Quantity = 70,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9288)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 6,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9313),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9316),
                            IsDeleted = false,
                            Price = 84.60m,
                            Quantity = 26,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9314)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 7,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9330),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9334),
                            IsDeleted = false,
                            Price = 91.81m,
                            Quantity = 35,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9332)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 8,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9356),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9360),
                            IsDeleted = false,
                            Price = 22.22m,
                            Quantity = 67,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9358)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 9,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9375),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9378),
                            IsDeleted = false,
                            Price = 74.32m,
                            Quantity = 95,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9377)
                        },
                        new
                        {
                            StoreId = 3,
                            ItemId = 10,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9401),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9405),
                            IsDeleted = false,
                            Price = 5.15m,
                            Quantity = 11,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9403)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 1,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9422),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9426),
                            IsDeleted = false,
                            Price = 88.83m,
                            Quantity = 7,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9424)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 2,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9448),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9451),
                            IsDeleted = false,
                            Price = 37.78m,
                            Quantity = 99,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9450)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 3,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9467),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9470),
                            IsDeleted = false,
                            Price = 64.32m,
                            Quantity = 40,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9469)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 4,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9498),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9502),
                            IsDeleted = false,
                            Price = 58.87m,
                            Quantity = 92,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9500)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 5,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9516),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9520),
                            IsDeleted = false,
                            Price = 70.88m,
                            Quantity = 44,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9518)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 6,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9541),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9545),
                            IsDeleted = false,
                            Price = 39.70m,
                            Quantity = 20,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9543)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 7,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9560),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9564),
                            IsDeleted = false,
                            Price = 11.92m,
                            Quantity = 57,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9562)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 8,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9586),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9589),
                            IsDeleted = false,
                            Price = 78.25m,
                            Quantity = 38,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9588)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 9,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9605),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9608),
                            IsDeleted = false,
                            Price = 39.45m,
                            Quantity = 33,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9607)
                        },
                        new
                        {
                            StoreId = 4,
                            ItemId = 10,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9630),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9634),
                            IsDeleted = false,
                            Price = 67.36m,
                            Quantity = 33,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9632)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 1,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9650),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9654),
                            IsDeleted = false,
                            Price = 66.92m,
                            Quantity = 57,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9652)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 2,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9676),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9679),
                            IsDeleted = false,
                            Price = 65.13m,
                            Quantity = 54,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9678)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 3,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9694),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9698),
                            IsDeleted = false,
                            Price = 0.92m,
                            Quantity = 77,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9696)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 4,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9720),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9723),
                            IsDeleted = false,
                            Price = 25.80m,
                            Quantity = 60,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9722)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 5,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9738),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9742),
                            IsDeleted = false,
                            Price = 75.96m,
                            Quantity = 57,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9740)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 6,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9764),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9767),
                            IsDeleted = false,
                            Price = 6.30m,
                            Quantity = 7,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9766)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 7,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9782),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9786),
                            IsDeleted = false,
                            Price = 61.74m,
                            Quantity = 71,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9784)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 8,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9807),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9811),
                            IsDeleted = false,
                            Price = 90.47m,
                            Quantity = 83,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9809)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 9,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9826),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9829),
                            IsDeleted = false,
                            Price = 81.59m,
                            Quantity = 35,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9828)
                        },
                        new
                        {
                            StoreId = 5,
                            ItemId = 10,
                            CreatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9851),
                            DeletedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9855),
                            IsDeleted = false,
                            Price = 51.51m,
                            Quantity = 92,
                            UpdatedDate = new DateTime(2024, 4, 10, 21, 51, 25, 839, DateTimeKind.Local).AddTicks(9853)
                        });
                });

            modelBuilder.Entity("DAL.StoreItem", b =>
                {
                    b.HasOne("DAL.Item", "Item")
                        .WithMany("StoreItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Store", "Store")
                        .WithMany("StoreItems")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DAL.Item", b =>
                {
                    b.Navigation("StoreItems");
                });

            modelBuilder.Entity("DAL.Store", b =>
                {
                    b.Navigation("StoreItems");
                });
#pragma warning restore 612, 618
        }
    }
}
